"""Vanilla RCT2 (plus Deluxe WW/TT shops) coverage lists.

These ids are the checklist the sim must implement. They follow OpenRCT2's
`Ride.h` ride-type table (slots 0–90, skipping unused/alt), `ShopItem.h`
sellable goods, RCT2 terrain surfaces, weather, path types, ride music,
and `Audio.h` SoundId through `portcullis` (kRCT2SoundCount).
"""

from __future__ import annotations

# Official RCT2 ride types. Ids match our catalog. Unused DAT slots (1D, 1F,
# 22, 50, 52–55, 59) and *_ALT track variants are not attractions.
RCT2_RIDES: dict[str, str] = {
    "spiral_coaster": "Spiral Roller Coaster",
    "stand_up_coaster": "Stand-up Roller Coaster",
    "suspended_swinging": "Suspended Swinging Coaster",
    "inverted_coaster": "Inverted Roller Coaster",
    "junior_coaster": "Junior Roller Coaster",
    "miniature_railway": "Miniature Railway",
    "monorail": "Monorail",
    "mini_suspended_coaster": "Mini Suspended Coaster",
    "boat_hire": "Boat Hire",
    "wooden_wild_mouse": "Wooden Wild Mouse",
    "steeplechase": "Steeplechase",
    "car_ride": "Car Ride",
    "launched_freefall": "Launched Freefall",
    "bobsleigh": "Bobsleigh Coaster",
    "observation_tower": "Observation Tower",
    "looping_coaster": "Looping Roller Coaster",
    "dinghy_slide": "Dinghy Slide",
    "mine_train": "Mine Train Coaster",
    "chairlift": "Chairlift",
    "corkscrew": "Corkscrew Roller Coaster",
    "maze": "Hedge Maze",
    "spiral_slide": "Spiral Slide",
    "go_karts": "Go-Karts",
    "log_flume": "Log Flume",
    "river_rapids": "River Rapids",
    "dodgems": "Dodgems",
    "swinging_ship": "Swinging Ship",
    "swinging_inverter_ship": "Swinging Inverter Ship",
    "merry_go_round": "Merry-Go-Round",
    "ferris_wheel": "Ferris Wheel",
    "motion_simulator": "Motion Simulator",
    "cinema_3d": "3D Cinema",
    "top_spin": "Top Spin",
    "space_rings": "Space Rings",
    "reverse_freefall_coaster": "Reverse Freefall Coaster",
    "lift": "Lift",
    "vertical_drop_coaster": "Vertical Drop Roller Coaster",
    "twist": "Twist",
    "haunted_house": "Haunted House",
    "circus": "Circus",
    "ghost_train": "Ghost Train",
    "twister_coaster": "Twister Roller Coaster",
    "wooden_coaster": "Wooden Roller Coaster",
    "side_friction": "Side-Friction Roller Coaster",
    "steel_wild_mouse": "Steel Wild Mouse",
    "multi_dimension_coaster": "Multi-Dimension Roller Coaster",
    "flying_coaster": "Flying Roller Coaster",
    "virginia_reel": "Virginia Reel",
    "splash_boats": "Splash Boats",
    "mini_helicopters": "Mini Helicopters",
    "lay_down_coaster": "Lay-down Roller Coaster",
    "suspended_monorail": "Suspended Monorail",
    "reverser_coaster": "Reverser Roller Coaster",
    "heartline_twister": "Heartline Twister Coaster",
    "mini_golf": "Mini Golf",
    "giga_coaster": "Giga Coaster",
    "roto_drop": "Roto-Drop",
    "flying_saucers": "Flying Saucers",
    "crooked_house": "Crooked House",
    "monorail_cycles": "Monorail Cycles",
    "compact_inverted": "Compact Inverted Coaster",
    "water_coaster": "Water Coaster",
    "air_powered_vertical": "Air Powered Vertical Coaster",
    "inverted_hairpin": "Inverted Hairpin Coaster",
    "magic_carpet": "Magic Carpet",
    "submarine_ride": "Submarine Ride",
    "river_rafts": "River Rafts",
    "enterprise": "Enterprise",
    "inverted_impulse": "Inverted Impulse Coaster",
    "mini_roller_coaster": "Mini Roller Coaster",
    "mine_ride": "Mine Ride",
    "lim_launched": "LIM Launched Roller Coaster",
}

# ShopItem.h sellable goods (not empty containers, admission, or on-ride photos).
RCT2_SHOPS: dict[str, str] = {
    "balloon_stall": "Balloon Stall",
    "toy_stall": "Toy Stall",
    "information_kiosk": "Information Kiosk",
    "photo_stall": "Souvenir Photos",
    "umbrella_stall": "Umbrella Stall",
    "drinks_stall": "Drinks Stall",
    "burger_bar": "Burger Bar",
    "fries_stall": "Fries Stall",
    "ice_cream": "Ice Cream Stall",
    "candyfloss": "Candyfloss Stall",
    "pizza_stall": "Pizza Stall",
    "popcorn": "Popcorn Stall",
    "hot_dog": "Hot Dog Stall",
    "seafood": "Seafood Stall",
    "hat_stall": "Hat Stall",
    "toffee_apple": "Toffee Apple Stall",
    "tshirt_stall": "T-Shirt Stall",
    "doughnut": "Doughnut Stall",
    "coffee": "Coffee Shop",
    "chicken": "Fried Chicken Stall",
    "lemonade": "Lemonade Stall",
    "pretzel": "Pretzel Stall",
    "hot_chocolate": "Hot Chocolate Stall",
    "iced_tea": "Iced Tea Stall",
    "funnel_cake": "Funnel Cake Stall",
    "sunglasses": "Sunglasses Stall",
    "beef_noodles": "Beef Noodles Stall",
    "fried_rice_noodles": "Fried Rice Noodles Stall",
    "wonton_soup": "Wonton Soup Stall",
    "meatball_soup": "Meatball Soup Stall",
    "fruit_juice": "Fruit Juice Stall",
    "soybean_milk": "Soybean Milk Stall",
    "sujeonggwa": "Sujeonggwa Stall",
    "sub_sandwich": "Sub Sandwich Stall",
    "cookie": "Cookie Shop",
    "roast_sausage": "Roast Sausage Stall",
    "toilets": "Toilets",
    "first_aid": "First Aid Room",
    "cash_machine": "Cash Machine",
    "souvenir_stall": "Souvenir Stall",
}

# Path items + scenery-window groups from the RCT2 construction window.
RCT2_SCENERY: dict[str, str] = {
    "tree": "Tree",
    "oak": "Oak Tree",
    "pine": "Pine Tree",
    "palm": "Palm Tree",
    "cactus": "Cactus",
    "snow_tree": "Snow Tree",
    "shrub": "Shrub",
    "hedge": "Hedge",
    "garden": "Garden",
    "flower_bed": "Flower Bed",
    "topiary": "Topiary",
    "bench": "Bench",
    "lamp": "Lamp",
    "bin": "Litter Bin",
    "jumping_fountain": "Jumping Fountain",
    "queue_tv": "Queue-Line TV",
    "fence": "Wooden Fence",
    "iron_fence": "Iron Fence",
    "wall": "Brick Wall",
    "castle_wall": "Castle Wall",
    "statue": "Park Statue",
    "fountain": "Fountain",
    "classical": "Classical Column",
    "egyptian": "Egyptian Obelisk",
    "jungle": "Jungle Ruin",
    "martian": "Martian Sculpture",
    "wonderland": "Wonderland Prop",
    "jurassic": "Jurassic Fossil",
    "pagoda": "Pagoda Piece",
    "mine": "Mine Timber",
    "medieval": "Medieval Banner",
    "space": "Space Antenna",
    "creepy": "Creepy Gravestone",
    "urban": "City Planter",
}

RCT2_TERRAIN: tuple[str, ...] = (
    "grass",
    "sand",
    "dirt",
    "rock",
    "martian",
    "chequerboard",
    "grass_clumps",
    "ice",
    "grid",
    "sand_red",
    "sand_brown",
)

RCT2_PATHS: tuple[str, ...] = (
    "dirt",
    "crazy",
    "cobblestone",
    "tarmac",
    "tile",
    "queue",
)

# OpenRCT2 WeatherState names used by RCT2.
RCT2_WEATHER: tuple[str, ...] = (
    "sunny",
    "partial",
    "cloudy",
    "rain",
    "heavy_rain",
    "thunder",
)

RCT2_MUSIC: tuple[str, ...] = (
    "dodgems",
    "fairground_organ",
    "roman_fanfare",
    "oriental",
    "martian",
    "jungle_drums",
    "egyptian",
    "toyland",
    "space",
    "horror",
    "techno",
    "gentle",
    "summer",
    "water",
    "wild_west",
    "jurassic",
    "rock_1",
    "ragtime",
    "fantasy",
    "rock_2",
    "ice",
    "snow",
    "custom_1",
    "custom_2",
    "medieval",
    "urban",
    "organ",
    "mechanical",
    "modern",
    "pirate",
    "rock_3",
    "candy",
)

# Audio.h SoundId through portcullis (vanilla RCT2 count).
RCT2_SOUNDS: tuple[str, ...] = (
    "lift_classic",
    "track_friction_classic_wood",
    "friction_classic",
    "scream_1",
    "click_1",
    "click_2",
    "place_item",
    "scream_2",
    "scream_3",
    "scream_4",
    "scream_5",
    "scream_6",
    "lift_friction_wheels",
    "purchase",
    "crash",
    "laying_out_water",
    "water_1",
    "water_2",
    "train_whistle",
    "train_departing",
    "water_splash",
    "go_kart_engine",
    "ride_launch_1",
    "ride_launch_2",
    "cough_1",
    "cough_2",
    "cough_3",
    "cough_4",
    "rain",
    "thunder_1",
    "thunder_2",
    "track_friction_train",
    "track_friction_water",
    "balloon_pop",
    "mechanic_fix",
    "scream_7",
    "toilet_flush",
    "click_3",
    "quack",
    "news_item",
    "window_open",
    "laugh_1",
    "laugh_2",
    "laugh_3",
    "applause",
    "haunted_house_scare",
    "haunted_house_scream_1",
    "haunted_house_scream_2",
    "block_brake_close",
    "block_brake_release",
    "error",
    "brake_release",
    "lift_arrow",
    "lift_wood",
    "track_friction_wood",
    "lift_wild_mouse",
    "lift_bm",
    "track_friction_bm",
    "scream_8",
    "tram",
    "door_open",
    "door_close",
    "portcullis",
)

RCT2_STAFF: tuple[str, ...] = ("handyman", "mechanic", "security", "entertainer")

RCT2_ENTERTAINER_COSTUMES: tuple[str, ...] = (
    "panda",
    "tiger",
    "elephant",
    "roman",
    "gorilla",
    "snowman",
    "knight",
    "astronaut",
    "bandit",
    "sheriff",
    "pirate",
)
